name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [01/dotnet6/sonar.csproj, 02/dotnet6/magnitude.csproj, 03/dotnet6/binary.csproj, 04/dotnet6/bingo.csproj, 05/dotnet6/vents.csproj]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Execute all unit tests in the solution
    - name: Run the program
      run: dotnet run --project ${{ matrix.configuration }}
