name: Maven CI

on:
  push:
    paths:
      - "**/java11/**"
      - ".github/workflows/maven*.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/java11/**"
      - ".github/workflows/maven*.yml"

jobs:
  build:
    strategy:
      matrix:
        configuration: [01/maven]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn compile
      - name: Run with Maven
        run: exec:java -Dexec.mainClass=aoc2021.Aoc