name: Python Run

on:
  push:
    paths:
      - '**/python/**'
      - '.github/workflows/python*.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '**/python/**'
      - '.github/workflows/python*.yml'
jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        configuration: [01/python/sonar.py, 02/python/magnitude.py, 03/python/binary.py]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Run
      run: python  ${{ matrix.configuration }}