name: Python

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        configuration: [01/python/sonar.py, 02/python/magnitude.py]
        tests: [02/python]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: test
      run: cd ${{ matrix.tests}} && python -m unittest
    - name: Run
      run: python  ${{ matrix.configuration }}