name: Python Tests

on:
  push:
    paths:
      - '**/python/**'
      - '.github/workflows/python*.yml'

  pull_request:
    branches: [ main ]
    paths:
      - '**/python/**'
      - '.github/workflows/python*.yml'

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        tests: [01/python, 02/python, 03/python]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: test
      run: cd ${{ matrix.tests}} && python -m unittest
